### ISSUE TITLE
Installation trouble in "editable" mode

### ISSUE THREAD

**Issue by BDonnot** [powsybl/pypowsybl#116]
* **Do you want to request a *feature* or report a *bug*?**
This is a bug report

* **What is the current behavior?**
When trying to install, from source, pyposybl with the provided command (`python3 -m pip install --user .`) everything works fine (after following the tutorial and installing graalvm and everything).

I wanted to make some modification on python layer (basically to try the features like `update_generators_with_data_frame` or `update_loads_with_data_frame`) to develop a grid2op `Backend` (see `https://github.com/rte-france/Grid2Op`). To that end, it is often useful to install a package in "editable" mode (so that the modifcation of the python layer can be made without having to reinstall the package: see https://pip.pypa.io/en/stable/cli/pip_install/#install-editable).
To do that, one normally types: `python3 -m pip install --user --editable .` but for pypowsybl it does not work, for me with an error like:

```
WARNING: Ignoring invalid distribution -ypowsybl (/home/benjamin/.local/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -ypowsybl (/home/benjamin/.local/lib/python3.8/site-packages)
Obtaining file:///home/benjamin/Documents/pypowsybl
  WARNING: Ignoring invalid distribution -ypowsybl (/home/benjamin/.local/lib/python3.8/site-packages)
Requirement already satisfied: prettytable in /home/benjamin/.local/lib/python3.8/site-packages (from pypowsybl==0.8.0) (2.1.0)
Requirement already satisfied: pandas in /home/benjamin/.local/lib/python3.8/site-packages (from pypowsybl==0.8.0) (1.1.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/benjamin/.local/lib/python3.8/site-packages (from pandas->pypowsybl==0.8.0) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/lib/python3/dist-packages (from pandas->pypowsybl==0.8.0) (2019.3)
Requirement already satisfied: numpy>=1.15.4 in /home/benjamin/.local/lib/python3.8/site-packages (from pandas->pypowsybl==0.8.0) (1.20.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7.3->pandas->pypowsybl==0.8.0) (1.14.0)
Requirement already satisfied: wcwidth in /home/benjamin/.local/lib/python3.8/site-packages (from prettytable->pypowsybl==0.8.0) (0.1.9)
WARNING: Ignoring invalid distribution -ypowsybl (/home/benjamin/.local/lib/python3.8/site-packages)
Installing collected packages: pypowsybl
  Attempting uninstall: pypowsybl
    WARNING: Ignoring invalid distribution -ypowsybl (/home/benjamin/.local/lib/python3.8/site-packages)
    Found existing installation: pypowsybl 0.8.0
    Uninstalling pypowsybl-0.8.0:
      Successfully uninstalled pypowsybl-0.8.0
  Running setup.py develop for pypowsybl
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/benjamin/Documents/pypowsybl/setup.py'"'"'; __file__='"'"'/home/benjamin/Documents/pypowsybl/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=
         cwd: /home/benjamin/Documents/pypowsybl/
    Complete output (73 lines):
    running develop
    running egg_info
    writing pypowsybl.egg-info/PKG-INFO
    writing dependency_links to pypowsybl.egg-info/dependency_links.txt
    writing requirements to pypowsybl.egg-info/requires.txt
    writing top-level names to pypowsybl.egg-info/top_level.txt
    adding license file 'LICENSE' (matched pattern 'LICEN[CS]E*')
    reading manifest file 'pypowsybl.egg-info/SOURCES.txt'
    writing manifest file 'pypowsybl.egg-info/SOURCES.txt'
    running build_ext
    -- pybind11 v2.6.1 dev1
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/benjamin/Documents/pypowsybl/build/temp.linux-x86_64-3.8
    [ 42%] Built target mvn
    [ 47%] Performing patch step for 'native-image'
    [pypowsybl-java:1045409]    classlist:   3,847.30 ms,  1.19 GB
    [pypowsybl-java:1045409]        (cap):     338.30 ms,  1.19 GB
    [pypowsybl-java:1045409]        setup:     839.29 ms,  1.19 GB
    Error: Error compiling query code (in /tmp/SVM-15243784308829704977/Directives.c). Compiler command '/usr/bin/gcc -Wall -Werror -o /tmp/SVM-15243784308829704977/Directives /tmp/SVM-15243784308829704977/Directives.c ' output included error: /tmp/SVM-15243784308829704977/Directives.c:243:190: error: ‘load_flow_component_result’ {aka ‘struct load_flow_component_result_struct’} has no member named ‘component_num’
        type com.powsybl.python.PyPowsyblApiHeader$LoadFlowComponentResultPointer
        C file contents around line 243:
        /tmp/SVM-15243784308829704977/Directives.c:242:     printf("NativeCodeInfo:Directives:StructInfo:load_flow_component_result:PropertyInfo:size=%lu\n", ((unsigned long)sizeof(load_flow_component_result)));
        /tmp/SVM-15243784308829704977/Directives.c:243:     printf("NativeCodeInfo:Directives:StructInfo:load_flow_component_result:StructFieldInfo:component_num:PropertyInfo:size=%lu\n", ((unsigned long)sizeof(((load_flow_component_result *) 0)->component_num)));
        /tmp/SVM-15243784308829704977/Directives.c:244:     printf("NativeCodeInfo:Directives:StructInfo:load_flow_component_result:StructFieldInfo:component_num:PropertyInfo:offset=%lu\n", ((unsigned long)offsetof(load_flow_component_result, component_num)));
    Error: Error compiling query code (in /tmp/SVM-15243784308829704977/Directives.c). Compiler command '/usr/bin/gcc -Wall -Werror -o /tmp/SVM-15243784308829704977/Directives /tmp/SVM-15243784308829704977/Directives.c ' output included error: /tmp/SVM-15243784308829704977/Directives.c:244:151: error: ‘load_flow_component_result’ {aka ‘struct load_flow_component_result_struct’} has no member named ‘component_num’
        method com.powsybl.python.PyPowsyblApiHeader$LoadFlowComponentResultPointer.geComponentNum()
        C file contents around line 244:
        /tmp/SVM-15243784308829704977/Directives.c:243:     printf("NativeCodeInfo:Directives:StructInfo:load_flow_component_result:StructFieldInfo:component_num:PropertyInfo:size=%lu\n", ((unsigned long)sizeof(((load_flow_component_result *) 0)->component_num)));
        /tmp/SVM-15243784308829704977/Directives.c:244:     printf("NativeCodeInfo:Directives:StructInfo:load_flow_component_result:StructFieldInfo:component_num:PropertyInfo:offset=%lu\n", ((unsigned long)offsetof(load_flow_component_result, component_num)));
        /tmp/SVM-15243784308829704977/Directives.c:245:     {
    Error: Error compiling query code (in /tmp/SVM-15243784308829704977/Directives.c). Compiler command '/usr/bin/gcc -Wall -Werror -o /tmp/SVM-15243784308829704977/Directives /tmp/SVM-15243784308829704977/Directives.c ' output included error: /tmp/SVM-15243784308829704977/Directives.c:250:20: error: ‘load_flow_component_result’ {aka ‘struct load_flow_component_result_struct’} has no member named ‘component_num’
        C file contents around line 250:
        /tmp/SVM-15243784308829704977/Directives.c:249:         memset(&fieldHolder, 0x0, sizeof(fieldHolder));
        /tmp/SVM-15243784308829704977/Directives.c:250:         fieldHolder.component_num = all_bits_set;
        /tmp/SVM-15243784308829704977/Directives.c:251:         is_unsigned = fieldHolder.component_num > 0;
    Error: Error compiling query code (in /tmp/SVM-15243784308829704977/Directives.c). Compiler command '/usr/bin/gcc -Wall -Werror -o /tmp/SVM-15243784308829704977/Directives /tmp/SVM-15243784308829704977/Directives.c ' output included error: /tmp/SVM-15243784308829704977/Directives.c:251:34: error: ‘load_flow_component_result’ {aka ‘struct load_flow_component_result_struct’} has no member named ‘component_num’
        C file contents around line 251:
        /tmp/SVM-15243784308829704977/Directives.c:250:         fieldHolder.component_num = all_bits_set;
        /tmp/SVM-15243784308829704977/Directives.c:251:         is_unsigned = fieldHolder.component_num > 0;
        /tmp/SVM-15243784308829704977/Directives.c:252:         printf("NativeCodeInfo:Directives:StructInfo:load_flow_component_result:StructFieldInfo:component_num:PropertyInfo:signedness=$%s$\n", (is_unsigned) ? "UNSIGNED" : "SIGNED");
    Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
    Error: Image build request failed with exit status 1
    make[2]: *** [CMakeFiles/native-image.dir/build.make:100: native-image-prefix/src/native-image-stamp/native-image-patch] Error 1
    make[1]: *** [CMakeFiles/Makefile2:127: CMakeFiles/native-image.dir/all] Error 2
    make: *** [Makefile:84: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/benjamin/Documents/pypowsybl/setup.py", line 142, in <module>
        setup(
      File "/home/benjamin/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/benjamin/.local/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/benjamin/.local/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/benjamin/Documents/pypowsybl/setup.py", line 82, in run
        self.build_extension(ext)
      File "/home/benjamin/Documents/pypowsybl/setup.py", line 116, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
    ----------------------------------------
  Rolling back uninstall of pypowsybl
  Moving to /home/benjamin/.local/lib/python3.8/site-packages/_pypowsybl.cpython-38-x86_64-linux-gnu.so
   from /tmp/pip-uninstall-tpzrl8vm/_pypowsybl.cpython-38-x86_64-linux-gnu.so
  Moving to /home/benjamin/.local/lib/python3.8/site-packages/pypowsybl-0.8.0-py3.8.egg-info
   from /home/benjamin/.local/lib/python3.8/site-packages/~-powsybl-0.8.0-py3.8.egg-info
  Moving to /home/benjamin/.local/lib/python3.8/site-packages/pypowsybl/
   from /home/benjamin/.local/lib/python3.8/site-packages/~-powsybl
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/benjamin/Documents/pypowsybl/setup.py'"'"'; __file__='"'"'/home/benjamin/Documents/pypowsybl/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix= Check the logs for full command output.
WARNING: Ignoring invalid distribution -ypowsybl (/home/benjamin/.local/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -ypowsybl (/home/benjamin/.local/lib/python3.8/site-packages)
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
As mentioned above:
- clone the pypowsyble repo
- setup the graalvm installation (and the `export JAVA_HOME=...`)
- type `python3 -m pip install --user --editable .`

* **What is the expected behavior?**

This command should run as the version without the `editable` flag

* **What is the motivation / use case for changing the behavior?**

Ease of development python side

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

```python
>>> pp.print_version()
Powsybl versions:
+-----------------------------+-----------------------+------------+------------------------------------------+-------------------------------+
| Repository name             | Maven project version | Git branch | Git version                              | Build timestamp               |
+-----------------------------+-----------------------+------------+------------------------------------------+-------------------------------+
| powsybl-open-loadflow       | 0.11.0                | UNKNOWN    | eb1f53612a03c0468a6156de89aacc4012674443 | 2021-05-27T09:50:07.767+02:00 |
| powsybl-single-line-diagram | 2.2.0                 | UNKNOWN    | b97b2d54108bad50fd2a9c1050bc0423f2499e86 | 2021-05-26T22:08:52.780+02:00 |
| powsybl-core                | 4.2.0                 | UNKNOWN    | 929bbaf93ff7bfb6481d04824c21e81b8800764f | 2021-05-25T11:14:38.408+02:00 |
| powsybl-rte-core            | 3.2.0                 | UNKNOWN    | 76c88c56886fd55b82bf0e76c8a2efeda55a75ce | 2021-05-27T11:29:00.743+02:00 |
+-----------------------------+-----------------------+------------+------------------------------------------+-------------------------------+
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by geofjamg** [comment]
It works on my computer. Could you try again to check if is was something else?
It seems you have dirty packages in your local repo ("WARNING: Ignoring invalid distribution -ypowsybl"). It looks like as if past pypowsybl installations have filled your /home/benjamin/.local/lib/python3.8/site-package with bad named packages.
Could you try to clean all theses  "-ypowsybl" and see if you don't have warnings anymore?

**Comment by BDonnot** [comment]
You are correct, removing the files:
- `rm -rf /home/benjamin/.local/lib/python3.8/site-packages/'~ypowsybl-0.8.0-py3.8.egg-info'`
- `rm -rf ls /home/benjamin/.local/lib/python3.8/site-packages/'~ypowsybl'`

And the `build` directory (`rm -rf build`, once cd in the root of the pypowsybl git repo) solved the issue.

Thanks for your help
