### ISSUE TITLE
Some error messages when installing from source

### ISSUE THREAD

**Issue by BDonnot** [powsybl/pypowsybl#118]
* **Do you want to request a *feature* or report a *bug*?**
This is a "bug" report for a "bug" that has absolutely no impact yet. However, it is using a deprecated behaviour of "pip" which will be removed "in the long run"

* **What is the current behavior?**
When trying to install pypowsyble from source, I can do it easily, but I encounter each time some error messages during the installation process (it might be related to #116 ):

```
Defaulting to user installation because normal site-packages is not writeable
WARNING: Ignoring invalid distribution -ypowsybl (/home/benjamin/.local/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -ypowsybl (/home/benjamin/.local/lib/python3.8/site-packages)
Processing /home/benjamin/Documents/pypowsybl
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Requirement already satisfied: prettytable in /home/benjamin/.local/lib/python3.8/site-packages (from pypowsybl==0.8.0) (2.1.0)
Requirement already satisfied: pandas in /home/benjamin/.local/lib/python3.8/site-packages (from pypowsybl==0.8.0) (1.1.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/benjamin/.local/lib/python3.8/site-packages (from pandas->pypowsybl==0.8.0) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/lib/python3/dist-packages (from pandas->pypowsybl==0.8.0) (2019.3)
Requirement already satisfied: numpy>=1.15.4 in /home/benjamin/.local/lib/python3.8/site-packages (from pandas->pypowsybl==0.8.0) (1.20.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7.3->pandas->pypowsybl==0.8.0) (1.14.0)
Requirement already satisfied: wcwidth in /home/benjamin/.local/lib/python3.8/site-packages (from prettytable->pypowsybl==0.8.0) (0.1.9)
Building wheels for collected packages: pypowsybl
  Building wheel for pypowsybl (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-63nna5as/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-63nna5as/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-thr_99n3
       cwd: /tmp/pip-req-build-63nna5as/
  Complete output (48 lines):
  running bdist_wheel
  running build
  running build_py
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/pypowsybl
  copying pypowsybl/__init__.py -> build/lib.linux-x86_64-3.8/pypowsybl
  copying pypowsybl/loadflow.py -> build/lib.linux-x86_64-3.8/pypowsybl
  copying pypowsybl/security.py -> build/lib.linux-x86_64-3.8/pypowsybl
  copying pypowsybl/util.py -> build/lib.linux-x86_64-3.8/pypowsybl
  copying pypowsybl/sensitivity.py -> build/lib.linux-x86_64-3.8/pypowsybl
  copying pypowsybl/network.py -> build/lib.linux-x86_64-3.8/pypowsybl
  creating build/lib.linux-x86_64-3.8/pypowsybl/grid2op_backend
  copying pypowsybl/grid2op_backend/__init__.py -> build/lib.linux-x86_64-3.8/pypowsybl/grid2op_backend
  copying pypowsybl/grid2op_backend/pypowsyblbackend.py -> build/lib.linux-x86_64-3.8/pypowsybl/grid2op_backend
  running build_ext
  CMake Error: The current CMakeCache.txt directory /tmp/pip-req-build-63nna5as/build/temp.linux-x86_64-3.8/CMakeCache.txt is different than the directory /home/benjamin/Documents/pypowsybl/build/temp.linux-x86_64-3.8 where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
  CMake Error: The source "/tmp/pip-req-build-63nna5as/cpp/CMakeLists.txt" does not match the source "/home/benjamin/Documents/pypowsybl/cpp/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-63nna5as/setup.py", line 142, in <module>
      setup(
    File "/home/benjamin/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/benjamin/.local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-63nna5as/setup.py", line 82, in run
      self.build_extension(ext)
    File "/tmp/pip-req-build-63nna5as/setup.py", line 115, in build_extension
      subprocess.check_call(['cmake', cpp_source_dir] + cmake_args, cwd=self.build_temp, env=env)
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-63nna5as/cpp', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-63nna5as/build/lib.linux-x86_64-3.8/', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DEXTRA_JARS=', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pypowsybl
  Running setup.py clean for pypowsybl
Failed to build pypowsybl
WARNING: Ignoring invalid distribution -ypowsybl (/home/benjamin/.local/lib/python3.8/site-packages)
Installing collected packages: pypowsybl
  Attempting uninstall: pypowsybl
    WARNING: Ignoring invalid distribution -ypowsybl (/home/benjamin/.local/lib/python3.8/site-packages)
    Found existing installation: pypowsybl 0.8.0
    Uninstalling pypowsybl-0.8.0:
      Successfully uninstalled pypowsybl-0.8.0
    Running setup.py install for pypowsybl ... done
  DEPRECATION: pypowsybl was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
WARNING: Ignoring invalid distribution -ypowsybl (/home/benjamin/.local/lib/python3.8/site-packages)
Successfully installed pypowsybl-0.8.0
WARNING: Ignoring invalid distribution -ypowsybl (/home/benjamin/.local/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -ypowsybl (/home/benjamin/.local/lib/python3.8/site-packages)
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
To reproduce it, you can run:
```bash
python3 -m pip install --user .
```

* **What is the expected behavior?**
Usually, there is no "ERROR" when installing a python package. Though these errors seem to have absolutely no impact on the installation process.

* **What is the motivation / use case for changing the behavior?**
Main motivation is to clean the installation process.
But it might also helps solving the bug described in #116 

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

I think this is related to #116 and might be caused by cmake, with the specific log:
```
CMake Error: The current CMakeCache.txt directory /tmp/pip-req-build-vuoivsis/build/temp.linux-x86_64-3.8/CMakeCache.txt is different than the directory /home/benjamin/Documents/pypowsybl/build/temp.linux-x86_64-3.8 where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
  CMake Error: The source "/tmp/pip-req-build-vuoivsis/cpp/CMakeLists.txt" does not match the source "/home/benjamin/Documents/pypowsybl/cpp/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
```

**NB** this is for now fine, but some information provided there: https://github.com/pypa/pip/issues/8368 might indicate that the python package installer will refuse to install such package in the future:
```
DEPRECATION: pypowsybl was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
```
(if a question doesn't apply, you can delete it)

**Comment by BDonnot** [comment]
After some more install, i think this is due to the wrong cleaning of the "build" directory. If you remove `rm -rf build` this directory, then the error does not appear again. 

This is still a bit weird to me

**Comment by sylvlecl** [comment]
Closing it: indeed it's more an issue with pip when switching between in-tree build and out-of-tree build.
