### ISSUE TITLE
Hades2 error

### ISSUE THREAD

**Issue by vincentbarbesant** [powsybl/pypowsybl#187]
* **Do you want to request a *feature* or report a *bug*?**

A bug

* **What is the current behavior?**

When I use Hades2 as provider for a loadflow, i get an error message (which seem to come from the java part)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
```
import os
import pypowsybl

from config import DATA_FOLDER

if __name__ == '__main__':
    pypowsybl.print_version()
    
    file = os.path.join(DATA_FOLDER, 'test_network.xiidm.bz2')

    network = pypowsybl.network.load(file)

    parameters = pypowsybl.loadflow.Parameters(voltage_init_mode=pypowsybl.loadflow.VoltageInitMode.DC_VALUES)

    pypowsybl.loadflow.run_ac(network, parameters)

    pypowsybl.loadflow.run_ac(network, parameters, provider='Hades2')
```
Error message at last line :
```
Jul 13, 2021 2:57:15 PM com.sun.xml.bind.v2.ClassFactory tryGetDeclaredConstructor
INFO: No default constructor found on class javax.xml.bind.annotation.adapters.CollapsedStringAdapter
java.lang.NoSuchMethodException: javax.xml.bind.annotation.adapters.CollapsedStringAdapter.<init>()
	at java.lang.Class.getConstructor0(DynamicHub.java:3349)
	at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2553)
	at com.sun.xml.bind.v2.ClassFactory.tryGetDeclaredConstructor(ClassFactory.java:137)
	at com.sun.xml.bind.v2.ClassFactory.create0(ClassFactory.java:106)
	at com.sun.xml.bind.v2.ClassFactory.create(ClassFactory.java:158)
	at com.sun.xml.bind.v2.runtime.Coordinator.getAdapter(Coordinator.java:102)
	at com.sun.xml.bind.v2.runtime.reflect.AdaptedAccessor.getAdapter(AdaptedAccessor.java:109)
	at com.sun.xml.bind.v2.runtime.reflect.AdaptedAccessor.set(AdaptedAccessor.java:83)
	at com.sun.xml.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.parse(TransducedAccessor.java:239)
	at com.sun.xml.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:212)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:577)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:556)
	at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:168)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:258)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:229)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:170)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:219)
	at com.rte_france.powsybl.iidm.export.adn.xml.jaxb.JaxbUtil.unmarchallReader(JaxbUtil.java:58)
	at com.rte_france.powsybl.iidm.export.adn.xml.jaxb.JaxbUtil.unmarchallReader(JaxbUtil.java:65)
	at com.rte_france.powsybl.hades2.Hades2Util.createInternalErrorException(Hades2Util.java:32)
	at com.rte_france.powsybl.hades2.Hades2Provider.after(Hades2Provider.java:167)
	at com.rte_france.powsybl.hades2.Hades2Provider$1.after(Hades2Provider.java:216)
	at com.rte_france.powsybl.hades2.Hades2Provider$1.after(Hades2Provider.java:196)
	at com.powsybl.computation.local.LocalComputationManager.doExecute(LocalComputationManager.java:348)
	at com.powsybl.computation.local.LocalComputationManager.lambda$execute$3(LocalComputationManager.java:327)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.powsybl.computation.CompletableFutureTask.run(CompletableFutureTask.java:43)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)

Traceback (most recent call last):
  File "D:\Users\barbesantvin\tension\asterix\test2.py", line 16, in <module>
    results = pypowsybl.loadflow.run_ac(network, parameters, provider='Hades2')
  File "D:\Users\barbesantvin\tension\asterix\venv\lib\site-packages\pypowsybl\loadflow.py", line 44, in run_ac
    return _pypowsybl.run_load_flow(network.ptr, False, parameters, provider)
_pypowsybl.PyPowsyblError: java.lang.NoSuchMethodError: javax.xml.bind.annotation.adapters.CollapsedStringAdapter.<init>()
```

* **What is the expected behavior?**
Loadflow should converge with both providers

* **Please tell us about your environment:**
  - PyPowsybl Version : 0.8.0  
  - PowSyBl Version: 

```
+-----------------------------+-----------------------+------------+------------------------------------------+-------------------------------+
| Repository name             | Maven project version | Git branch | Git version                              | Build timestamp               |
+-----------------------------+-----------------------+------------+------------------------------------------+-------------------------------+
| powsybl-open-loadflow       | 0.11.0                | UNKNOWN    | eb1f53612a03c0468a6156de89aacc4012674443 | 2021-05-27T09:50:07.767+02:00 |
| powsybl-single-line-diagram | 2.2.0                 | UNKNOWN    | b97b2d54108bad50fd2a9c1050bc0423f2499e86 | 2021-05-26T22:08:52.780+02:00 |
| powsybl-core                | 4.2.0                 | UNKNOWN    | 929bbaf93ff7bfb6481d04824c21e81b8800764f | 2021-05-25T11:14:38.408+02:00 |
| powsybl-rte-core            | 3.2.0                 | UNKNOWN    | 76c88c56886fd55b82bf0e76c8a2efeda55a75ce | 2021-05-27T11:29:00.743+02:00 |
+-----------------------------+-----------------------+------------+------------------------------------------+-------------------------------+
```
  - OS Version: Windows 10 Entreprise 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)
  - Hades2 version : V6.7.1.1

**Comment by geofjamg** [comment]
Could you try again with 0.9.0 ?

**Comment by sylvlecl** [comment]
So, eventually the exception was due to the use of an obsolete parameter in hades2 config (`useSAX: true`).
That parameter needs to be removed from hades2 integration, since it is not supported anymore.

However, it seems that it indeed makes us reach a point in java code which is not covered by native-image reflection config : 
it still needs to be updated to cover that edge case.
