### ISSUE TITLE
ModuleNotFoundError: No module named 'py4j'

### ISSUE THREAD

**Issue by BDonnot** [powsybl/pypowsybl#305]
* **Do you want to request a *feature* or report a *bug*?**
This is a bug

* **What is the current behavior?**
After installing pypowsybl from scratch:

```
python3 -m virtualenv venv
source venv/bin/activate
pip install pypowsybl
```
And then trying to install it:

```python
>>> import pypowsybl as pp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arthur_dent/bin/powsybl/pypowsybl/__init__.py", line 11, in <module>
    from py4j.java_gateway import JavaGateway, GatewayParameters
ModuleNotFoundError: No module named 'py4j'
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

see above

* **What is the expected behavior?**

There should not be any problem after a clean install

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: NC (cannot be loaded)
  - OS Version: ubuntu 20.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

python 3.8.10

**Comment by BDonnot** [comment]
EDIT: it seems to be a conflict with an old pypowsybl version, i'm investigating
