### ISSUE TITLE
Build fails at com.powsybl.python.security.SecurityAnalysisTest

### ISSUE THREAD

**Issue by makkes** [powsybl/pypowsybl#724]
### Describe the current behavior

I'm building pypowsybl on an M3 MacBook but it fails with the following output:

```
$ pip install .
[...]
[INFO] --- surefire:3.1.2:test (default-test) @ pypowsybl ---                                                                      
      [INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
      [INFO]                               
      [INFO] -------------------------------------------------------
      [INFO]  T E S T S                     
      [INFO] -------------------------------------------------------
      [INFO] Running com.powsybl.dataframe.network.adders.NetworkElementAddersTest
      [WARNING] Tests run: 19, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.198 s -- in com.powsybl.dataframe.network.adders.NetworkElementAddersTest
      [INFO] Running com.powsybl.dataframe.network.NetworkDataframesTest                                             
      [INFO] Tests run: 32, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.096 s -- in com.powsybl.dataframe.network.NetworkDataframesTest
      [INFO] Running com.powsybl.dataframe.DataframeMapperBuilderTest
      [INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s -- in com.powsybl.dataframe.DataframeMapperBuilderTest
      [INFO] Running com.powsybl.python.security.SecurityAnalysisTest
      [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.265 s <<< FAILURE! -- in com.powsybl.python.security.SecurityAnalysisTest
      [ERROR] com.powsybl.python.security.SecurityAnalysisTest.testStateMonitors -- Time elapsed: 0.251 s <<< FAILURE!             
      org.opentest4j.AssertionFailedError:
                                                                                                                                         
      Expecting actual:        
        [BranchResult{branchId='NHV1_NHV2_2', p1=302.4440491446602, q1=98.74027438014932, i1=456.7689759899921, p2=-300.43389523337305, q2=-137.1884930716406, i2=488.9927963672736, flowTransfer=NaN}]
      to contain exactly (and in same order):
        [BranchResult{branchId='NHV1_NHV2_2', p1=302.44404914466014, q1=98.74027438014933, i1=456.7689759899916, p2=-300.43389523337316, q2=-137.18849307164064, i2=488.99279636727357, flowTransfer=NaN}]
      but some elements were not found:
        [BranchResult{branchId='NHV1_NHV2_2', p1=302.44404914466014, q1=98.74027438014933, i1=456.7689759899916, p2=-300.43389523337316, q2=-137.18849307164064, i2=488.99279636727357, flowTransfer=NaN}]
      and others were not expected:
        [BranchResult{branchId='NHV1_NHV2_2', p1=302.4440491446602, q1=98.74027438014932, i1=456.7689759899921, p2=-300.43389523337305, q2=-137.1884930716406, i2=488.9927963672736, flowTransfer=NaN}]
                                                
          at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
          at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
          at com.powsybl.python.security.SecurityAnalysisTest.testStateMonitors(SecurityAnalysisTest.java:46)                     
          at java.base/java.lang.reflect.Method.invoke(Method.java:580)
          at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)                                                            
          at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

### Describe the expected behavior

The tests pass and the build succeeds.

### Describe the steps

Follow the instructions at https://github.com/powsybl/pypowsybl?tab=readme-ov-file#build-from-sources.

### Environment

- commit 2633ec1894e782ff4135c4fe40516bcf6f2d6d32
- Python 3.12.2
- java version "21.0.2" 2024-01-16 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30, mixed mode, sharing)

**Comment by geofjamg** [comment]
Thanks for the feedback. Should be fixed by #725. 
Be careful  not using Oracle GraalVM 21 but 17 instead because there is a regression in JDK 21 not yet solved: https://github.com/oracle/graal/issues/7759
